

source "https://rubygems.org"

gem "net-smtp", "~> 0.3"
gem "pony",     "~> 1.13"
gem "puma",     "~> 6.3"
gem "sinatra",  "~> 3.0"

gem "opentelemetry-sdk", "~> 1.2"
gem "opentelemetry-exporter-otlp", "~> 0.24"
gem "opentelemetry-instrumentation-all", "~> 0.39"
gem 'ddtrace', git: 'https://github.com/DataDog/dd-trace-rb', ref: '21c5f42ef98ee4f4c56b10a0f1edd254f10fd438'
